force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <displayFormat>BN-{0000}</displayFormat>
        <label>Bus Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Busses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled for Maintenance</fullName>
            </value>
            <value>
                <fullName>Undergoing Repairs</fullName>
            </value>
            <value>
                <fullName>Ready for Use</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Has_AC__c.field-meta.xml
<CustomField>
    <fullName>Has_AC__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has AC</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Maximum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Capacity__c</fullName>
    <label>Maximum Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <label>Odometer Reading</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Resale_Value__c.field-meta.xml
<CustomField>
    <fullName>Resale_Value__c</fullName>
    <label>Resale Value</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>1999</fullName>
            </value>
            <value>
                <fullName>1998</fullName>
            </value>
            <value>
                <fullName>1997</fullName>
            </value>
            <value>
                <fullName>1996</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus_Value_Configuration__mdt/Bus_Value_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Bus Value Configuration</label>
    <pluralLabel>Bus Value Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bus_Value_Configuration__mdt/fields/AC_Bonus__c.field-meta.xml
<CustomField>
    <fullName>AC_Bonus__c</fullName>
    <inlineHelpText>Percent bonus in value if bus has AC</inlineHelpText>
    <label>AC Bonus</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bus_Value_Configuration__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Is this configuration active?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bus_Value_Configuration__mdt/fields/Historic_Bonus__c.field-meta.xml
<CustomField>
    <fullName>Historic_Bonus__c</fullName>
    <inlineHelpText>Bonus to value if the bus is older than the Historic year (value is percent)</inlineHelpText>
    <label>Historic Bonus</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Bus_Value_Configuration__mdt/fields/Historic_Year__c.field-meta.xml
<CustomField>
    <fullName>Historic_Year__c</fullName>
    <inlineHelpText>Busses older than this year should be eligible for the historic bonus</inlineHelpText>
    <label>Historic Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2025</fullName>
                <default>true</default>
                <label>2025</label>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2003</fullName>
            </value>
            <value>
                <fullName>2002</fullName>
            </value>
            <value>
                <fullName>2001</fullName>
            </value>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>1999</fullName>
            </value>
            <value>
                <fullName>1998</fullName>
            </value>
            <value>
                <fullName>1997</fullName>
            </value>
            <value>
                <fullName>1996</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus_Value_Configuration__mdt/fields/Milage_Floor__c.field-meta.xml
<CustomField>
    <fullName>Milage_Floor__c</fullName>
    <inlineHelpText>Bus value does not begin to be impacted by milage until it has surpassed this value</inlineHelpText>
    <label>Milage Floor</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus_Value_Configuration__mdt/fields/Passenger_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Capacity__c</fullName>
    <inlineHelpText>Maximum number of passengers for this bus</inlineHelpText>
    <label>Passenger Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <default>true</default>
                <label>6</label>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus_Value_Configuration__mdt/fields/Starting_Value__c.field-meta.xml
<CustomField>
    <fullName>Starting_Value__c</fullName>
    <inlineHelpText>Starting resale value</inlineHelpText>
    <label>Starting Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus_Value_Configuration__mdt/fields/Value_Reduction__c.field-meta.xml
<CustomField>
    <fullName>Value_Reduction__c</fullName>
    <inlineHelpText>How much should the value of the bus decrease for each mile beyond the milage floor</inlineHelpText>
    <label>Value Reduction</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BusTriggerHandler.cls
public with sharing class BusTriggerHandler {
    public static void beforeInsert(Bus__c[] busList) {
        calculateBusValues(busList);
    }

    public static void beforeUpdate(Bus__c[] busList, Map<Id, Bus__c> oldBusMap){
        calculateBusValues(busList);
    }

    private static void calculateBusValues(Bus__c[] busList){
        Bus__c[] bussesToCalculateValue = new Bus__c[0];
        for(Bus__c bus : busList){
            if(bus.Current_Status__c == 'Ready for Use'){
                bussesToCalculateValue.add(bus);
            }
            else {
                bus.Resale_Value__c = 0;
            }
        }

        Bus__c[] bussesToUpdate = new Bus__c[0];

        Map<String, Bus_Value_Configuration__mdt> busValueMap = getConfigurations();
        if(busValueMap.isEmpty()) return;

        //get the defaultconfig
        Bus_Value_Configuration__mdt defaultConfig = busValueMap.containsKey('Default') ? busValueMap.get('Default') : null;

        for(Bus__c bus : bussesToCalculateValue){
            Bus_Value_Configuration__mdt matchingConfig = new Bus_Value_Configuration__mdt();
            if(bus.Maximum_Capacity__c != null && busValueMap.containsKey(bus.Maximum_Capacity__c)) {
                matchingConfig = busValueMap.get(bus.Maximum_Capacity__c);
            }
            else if(defaultConfig != null){
                matchingConfig = defaultConfig;
            } 
            
            if(matchingConfig != null){
                calculateBusValue(bus, matchingConfig);
            }
        }
    }

    private static void calculateBusValue(Bus__c bus, Bus_Value_Configuration__mdt config){
        Decimal value = config.Starting_Value__c;

        if(bus.Has_AC__c && config.AC_Bonus__c != null){
            value = value * (1 + (config.AC_Bonus__c / 100));
        }

        if(bus.Year__c != null && config.Historic_Year__c != null && config.Historic_Bonus__c != null && bus.Year__c <= config.Historic_Year__c){
            value = value * (1 + (config.Historic_Bonus__c / 100));
        }

        if(bus.Odometer_Reading__c != null && config.Milage_Floor__c != null && config.Value_Reduction__c != null && bus.Odometer_Reading__c > config.Milage_Floor__c){
            value -= ((bus.Odometer_Reading__c - config.Milage_Floor__c) * config.Value_Reduction__c);
        }

        bus.Resale_Value__c = value;
    }

    private static Map<String, Bus_Value_Configuration__mdt> getConfigurations(){
        Map<String, Bus_Value_Configuration__mdt> configMap = new Map<String, Bus_Value_Configuration__mdt>();
        for(Bus_Value_Configuration__mdt config : [
            SELECT AC_Bonus__c, Historic_Bonus__c, Historic_Year__c, Milage_Floor__c, Passenger_Capacity__c, Starting_Value__c, Value_Reduction__c
            FROM Bus_Value_Configuration__mdt
            WHERE Active__c = true
        ]){
            configMap.put(config.Passenger_Capacity__c, config);
        }

        return configMap;
    }
}