force-app/main/default/objects/Bus__c/Bus__c.object-meta.xml
<CustomObject>
    <label>Bus</label>
    <nameField>
        <displayFormat>BN-{0000}</displayFormat>
        <label>Bus Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Busses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bus__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled for Maintenance</fullName>
            </value>
            <value>
                <fullName>Undergoing Repairs</fullName>
            </value>
            <value>
                <fullName>Ready for Use</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Garage__c.field-meta.xml
<CustomField>
    <fullName>Garage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garage</label>
    <referenceTo>Garage__c</referenceTo>
    <relationshipLabel>Busses</relationshipLabel>
    <relationshipName>Busses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Maximum_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Capacity__c</fullName>
    <label>Maximum Capacity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bus__c/fields/Miles_Since_Last_Maintenance__c.field-meta.xml
<CustomField>
    <fullName>Miles_Since_Last_Maintenance__c</fullName>
    <formula>if(Odometer_Reading_Last_Maintenance__c = 0,
			-1,
			Odometer_Reading__c - Odometer_Reading_Last_Maintenance__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Miles Since Last Maintenance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus_Maintenance_Configuration__mdt/Bus_Maintenance_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Bus Maintenance Configuration</label>
    <pluralLabel>Bus Maintenance Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bus_Maintenance_Configuration__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Is this config active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bus_Maintenance_Configuration__mdt/fields/Maintenance_Interval__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Interval__c</fullName>
    <inlineHelpText>Number of miles between each maintenance</inlineHelpText>
    <label>Maintenance Interval</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bus_Maintenance_Configuration__mdt/fields/Maintenance_Type__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Type__c</fullName>
    <inlineHelpText>Type of maintenance needed</inlineHelpText>
    <label>Maintenance Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bus_Maintenance_Configuration__mdt/fields/Passenger_Capacity__c.field-meta.xml
<CustomField>
    <fullName>Passenger_Capacity__c</fullName>
    <inlineHelpText>Maximum number of passengers for this bus</inlineHelpText>
    <label>Passenger Capacity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>6</fullName>
                <default>true</default>
                <label>6</label>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>Default</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Garage__c/Garage__c.object-meta.xml
<CustomObject>
    <label>Garage</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Garage Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Garages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/Maintenance__c.object-meta.xml
<CustomObject>
    <label>Maintenance</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Maintenance Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance__c/fields/Bus__c.field-meta.xml
<CustomField>
    <fullName>Bus__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bus</label>
    <referenceTo>Bus__c</referenceTo>
    <relationshipLabel>Maintenance</relationshipLabel>
    <relationshipName>Maintenance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Garage__c.field-meta.xml
<CustomField>
    <fullName>Garage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Garage</label>
    <referenceTo>Garage__c</referenceTo>
    <relationshipLabel>Maintenance</relationshipLabel>
    <relationshipName>Maintenance</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Recorded_Odometer__c.field-meta.xml
<CustomField>
    <fullName>Recorded_Odometer__c</fullName>
    <label>Recorded Odometer</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Maintenance__c/fields/Schedule_Reason__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Reason__c</fullName>
    <label>Schedule Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MaintenanceSchedulerHandler.cls
public with sharing class MaintenanceSchedulerHandler {
    public static String prepQueryString(){
        String query = null;
        QueryInfo info = getQueryInfo();
        if(info.lowestInterval != 0){
            query = 'SELECT Id, Location__c, Miles_Since_Last_Maintenance__c, Maximum_Capacity__c, Garage__c, ' +
            '(SELECT Id, Schedule_Time__c, Recorded_Odometer__c FROM Maintenance__r ORDER BY Schedule_Time__c LIMIT 1) ' +
            'FROM Bus__c WHERE Current_Status__c = \'Ready for Use\' AND (Miles_Since_Last_Maintenance__c > ' + info.lowestInterval +  
            ' OR Miles_Since_Last_Maintenance__c < 0)';
        }
        return query;
    }

    public static QueryInfo getQueryInfo() {
        QueryInfo info = new QueryInfo();
        // info.countList = new String[0];
        info.lowestInterval = 0;
        for(Bus_Maintenance_Configuration__mdt config : [
            SELECT Passenger_Capacity__c, Maintenance_Interval__c 
            FROM  Bus_Maintenance_Configuration__mdt
            WHERE Active__c = TRUE
        ]){
            // info.countList.add('\'' + config.Passenger_Capacity__c + '\'');

            if(info.lowestInterval == 0 || config.Maintenance_Interval__c < info.lowestInterval){
                info.lowestInterval = config.Maintenance_Interval__c;
            }
        }

        return info;
    }

    public static void scheduleAppointments(Bus__c[] busList){
        BusMaintenanceInfo[] bussesForMaintenance = checkBussesForInterval(busList);
        if(!bussesForMaintenance.isEmpty()){
            createMaintenanceRecords(bussesForMaintenance);
        }
    }

    private static void createMaintenanceRecords(BusMaintenanceInfo[] busList){
        Maintenance__c[] maintenanceRecordsToInsert = new Maintenance__c[0];
        Garage__c[] garageList = getGarages();
        Bus__c[] bussesToUpdate = new Bus__c[0];
        for(BusMaintenanceInfo info : busList){
            Double dist;
            Id garageId = null;
            if(info.bus.Location__c == null){
                if(info.bus.Garage__c != null){
                    garageId = info.bus.Garage__c;
                } else {
                    //add an email/chatter post for when there is an issue
                    continue;
                }
            } else {
                for(Garage__c garage : garageList){
                    Double tempDist = Location.getDistance(info.bus.Location__c, garage.Location__c, 'mi');
                    if(garageId == null || tempDist < dist){
                        dist = tempDist;
                        garageId = garage.Id;
                    }
                }
            }
            
            System.debug('garageId: ' + garageId);

            Maintenance__c maint = new Maintenance__c(
                Bus__c = info.bus.Id,
                Garage__c = garageId,
                Schedule_Time__c = DateTime.now(),
                Schedule_Reason__c = info.config.Maintenance_Type__c
            );
            maintenanceRecordsToInsert.add(maint);
            info.bus.Current_Status__c = 'Scheduled for Maintenance';
            bussesToUpdate.add(info.bus);
        }

        System.debug('maintenanceRecordsToInsert: ' + maintenanceRecordsToInsert);
        if(!maintenanceRecordsToInsert.isEmpty()){
            insert maintenanceRecordsToInsert;
        }
        if(!bussesToUpdate.isEmpty()){
            update bussesToUpdate;
        }
    }

    private static Garage__c[] getGarages(){
        return [SELECT Id, Location__c FROM Garage__c WHERE Active__c = true];
    }

    private static BusMaintenanceInfo[] checkBussesForInterval(Bus__c[] busList){
        Map<String, Bus_Maintenance_Configuration__mdt> configMap = getConfigMap();
        Bus_Maintenance_Configuration__mdt defaultConfig = configMap.containsKey('Default') ? configMap.get('Default') : null;
        BusMaintenanceInfo[] bussesForMaintenance = new BusMaintenanceInfo[0];
        for(Bus__c bus : busList){
            Bus_Maintenance_Configuration__mdt matchingConfig = new Bus_Maintenance_Configuration__mdt();
            if(bus.Maximum_Capacity__c != null && configMap.containsKey(bus.Maximum_Capacity__c)){
                matchingConfig = configMap.get(bus.Maximum_Capacity__c);
            }
            else if(defaultConfig != null){
                matchingConfig = defaultConfig;
            }
            else {
                //skip this bus if there isn't a matching config
                continue;
            }
            BusMaintenanceInfo info = new BusMaintenanceInfo();
            if(bus.Miles_Since_Last_Maintenance__c > matchingConfig.Maintenance_Interval__c || bus.Miles_Since_Last_Maintenance__c < 0){
                info.bus = bus;
                info.config = matchingConfig;
                bussesForMaintenance.add(info);
            }
        }

        return bussesForMaintenance;
    }

    private static Map<String, Bus_Maintenance_Configuration__mdt> getConfigMap(){
        Map<String, Bus_Maintenance_Configuration__mdt> configMap = new Map<String, Bus_Maintenance_Configuration__mdt>();
        for(Bus_Maintenance_Configuration__mdt config : [
            SELECT Passenger_Capacity__c,  Maintenance_Interval__c, Maintenance_Type__c
            FROM Bus_Maintenance_Configuration__mdt 
            WHERE Active__c = true
        ]){
            configMap.put(config.Passenger_Capacity__c, config);
        }

        return configMap;
    }

    public class BusMaintenanceInfo{
        Bus__c bus;
        Bus_Maintenance_Configuration__mdt config;
    }

    public class QueryInfo{
        String[] countList;
        Decimal lowestInterval;
    }
}